import { InvoiceTemplateConfig } from '../types';

export const STANDARD_INVOICE_TEMPLATES: InvoiceTemplateConfig[] = [
  {
    id: 'TRADE_CLASSIC_TM',
    name: 'Classic Indian Trade & Retail (TM Format)',
    category: 'STANDARD',
    description: 'Authentic Indian GST Trade & Retail format matching standard hardware, electrical & consumer appliance tax invoices with full-height continuous vertical column borders, party mobile, CGST/SGST rate & amount split, tax summary matrix, and dual terms & receiver/authorized signature footer.',
    badge: 'Hardware & Retail',
    themeColor: '#000000',
    headerColor: '#ffffff',
    headerStyle: 'TRADE_CLASSIC',
    fontFamily: 'sans',
    tableStyle: 'BORDERED',
    showLogo: true,
    showPaymentMode: true,
    showCashDetails: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
    footerDeclaration: 'Goods once sold will not be taken back.',
  },
  {
    id: 'OFFICIAL_GST',
    name: 'Official GST Tax Master',
    category: 'STANDARD',
    description: 'Standard Government-compliant tax invoice with full CGST/SGST/IGST breakdown, HSN master summary, bank details, and authorized signature.',
    badge: 'Govt Standard',
    themeColor: '#1e293b', // Slate 800
    headerColor: '#f8fafc',
    headerStyle: 'MINIMAL_BORDERED',
    fontFamily: 'sans',
    tableStyle: 'BORDERED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
    footerDeclaration: 'Certified that the particulars given above are true and correct, and the amount indicated represents the price actually charged.',
    isDefault: true,
  },
  {
    id: 'MODERN_CLEAN',
    name: 'Modern Clean Corporate',
    category: 'STANDARD',
    description: 'Clean Indigo-accented layout with rounded cards, subtle badges, and modern typography suitable for tech, agencies, and consulting firms.',
    badge: 'Popular',
    themeColor: '#4f46e5', // Indigo 600
    headerColor: '#eef2ff',
    headerStyle: 'MODERN_SPLIT',
    fontFamily: 'sans',
    tableStyle: 'STRIPED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  },
  {
    id: 'CLASSIC_TALLY',
    name: 'Classic Tally Accounting',
    category: 'STANDARD',
    description: 'Traditional double-bordered Indian business accounting invoice layout familiar to Indian Chartered Accountants and Tally users.',
    badge: 'CA Favorite',
    themeColor: '#0f172a', // Slate 900
    headerColor: '#ffffff',
    headerStyle: 'BANNER',
    fontFamily: 'mono',
    tableStyle: 'BORDERED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
    footerDeclaration: 'Subject to Local Jurisdiction. E. & O.E.',
  },
  {
    id: 'EMERALD_PHARMA',
    name: 'Emerald Pharma & Healthcare',
    category: 'STANDARD',
    description: 'Fresh emerald green theme with prominent batch numbers, license codes, and clear warranty/guarantee notes.',
    badge: 'Pharma & FMCG',
    themeColor: '#059669', // Emerald 600
    headerColor: '#ecfdf5',
    headerStyle: 'BANNER',
    fontFamily: 'sans',
    tableStyle: 'STRIPED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
    headerTagline: 'Quality Health & Pharmaceutical Solutions',
  },
  {
    id: 'ROYAL_SAPPHIRE',
    name: 'Royal Sapphire Enterprise',
    category: 'STANDARD',
    description: 'Deep navy blue enterprise B2B format with prominent customer & shipping address cards and structured terms.',
    badge: 'B2B Enterprise',
    themeColor: '#1e3a8a', // Blue 900
    headerColor: '#eff6ff',
    headerStyle: 'BANNER',
    fontFamily: 'serif',
    tableStyle: 'BOXED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  },
  {
    id: 'VIBRANT_SUNSET',
    name: 'Vibrant Sunset Hardware',
    category: 'STANDARD',
    description: 'Warm amber & orange accent design with highlighted total amounts and high visibility for traders, distributors & retail hardware.',
    badge: 'Retail & Hardware',
    themeColor: '#d97706', // Amber 600
    headerColor: '#fffbeb',
    headerStyle: 'MODERN_SPLIT',
    fontFamily: 'sans',
    tableStyle: 'STRIPED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  },
  {
    id: 'MINIMAL_MONO',
    name: 'Minimal Clean Slate (B&W)',
    category: 'STANDARD',
    description: 'Ultra-clean high contrast black and white editorial layout. Saves printer ink and provides a modern minimalist appearance.',
    badge: 'Ink Saver',
    themeColor: '#000000',
    headerColor: '#ffffff',
    headerStyle: 'MINIMAL_BORDERED',
    fontFamily: 'sans',
    tableStyle: 'MINIMAL',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  },
  {
    id: 'RUBY_CRIMSON',
    name: 'Ruby Crimson Electronics',
    category: 'STANDARD',
    description: 'Bold red accent style tailored for mobile phones, consumer electronics, and appliances with prominent Sr. No. & IMEI tracking.',
    badge: 'Electronics & Gadgets',
    themeColor: '#dc2626', // Red 600
    headerColor: '#fef2f2',
    headerStyle: 'MODERN_SPLIT',
    fontFamily: 'sans',
    tableStyle: 'BOXED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
    headerTagline: 'Authorized Electronics & Appliances Sales',
  },
  {
    id: 'COMPACT_DENSE',
    name: 'Compact 1-Page Dense A4',
    category: 'STANDARD',
    description: 'Space-optimized high-density table structure engineered to fit large invoices with 15+ line items into a single pristine A4 sheet.',
    badge: '1-Page Fit',
    themeColor: '#334155', // Slate 700
    headerColor: '#f1f5f9',
    headerStyle: 'MINIMAL_BORDERED',
    fontFamily: 'sans',
    tableStyle: 'BORDERED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: false,
    showAmountInWords: true,
    showHsnSummaryTable: false,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  },
  {
    id: 'THERMAL_POS',
    name: 'Thermal POS Slip (80mm)',
    category: 'POS',
    description: 'Compact 80mm roll receipt optimized for point-of-sale thermal receipt printers with instant UPI payment QR code.',
    badge: 'POS Thermal',
    themeColor: '#0f172a',
    headerColor: '#ffffff',
    headerStyle: 'THERMAL',
    fontFamily: 'mono',
    tableStyle: 'MINIMAL',
    showLogo: false,
    showUpiQr: true,
    showBankDetails: false,
    showSignature: false,
    showTerms: false,
    showNotes: true,
    showAmountInWords: false,
    showHsnSummaryTable: false,
    showCopyTypeBadge: false,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  },
  {
    id: 'CREATIVE_LUXE',
    name: 'Creative Studio Luxe (Violet)',
    category: 'STANDARD',
    description: 'Sophisticated royal purple gradient theme crafted for creative agencies, design studios, software firms, and premium boutiques.',
    badge: 'Design & Creative',
    themeColor: '#7c3aed', // Violet 600
    headerColor: '#f5f3ff',
    headerStyle: 'BANNER',
    fontFamily: 'sans',
    tableStyle: 'STRIPED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  },
  {
    id: 'CORPORATE_TEAL',
    name: 'Corporate Dual-Tone Teal',
    category: 'STANDARD',
    description: 'Modern corporate teal & slate dual-tone layout for architectural, engineering, consulting, and manufacturing firms.',
    badge: 'Dual-Tone Pro',
    themeColor: '#0d9488', // Teal 600
    headerColor: '#f0fdfa',
    headerStyle: 'MODERN_SPLIT',
    fontFamily: 'sans',
    tableStyle: 'BORDERED',
    showLogo: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
  }
];

export const COLOR_PALETTES = [
  { name: 'Indigo Corporate', hex: '#4f46e5', lightHex: '#eef2ff' },
  { name: 'Official Slate', hex: '#1e293b', lightHex: '#f8fafc' },
  { name: 'Royal Navy', hex: '#1e3a8a', lightHex: '#eff6ff' },
  { name: 'Emerald Green', hex: '#059669', lightHex: '#ecfdf5' },
  { name: 'Ruby Crimson', hex: '#dc2626', lightHex: '#fef2f2' },
  { name: 'Sunset Amber', hex: '#d97706', lightHex: '#fffbeb' },
  { name: 'Violet Luxe', hex: '#7c3aed', lightHex: '#f5f3ff' },
  { name: 'Teal Dual-Tone', hex: '#0d9488', lightHex: '#f0fdfa' },
  { name: 'Rose Blossom', hex: '#e11d48', lightHex: '#fff1f2' },
  { name: 'Cyan Sky', hex: '#0284c7', lightHex: '#f0f9ff' },
  { name: 'Charcoal Black', hex: '#18181b', lightHex: '#fafafa' },
];

export interface TextColorThemePreset {
  id: string;
  name: string;
  description: string;
  textColor: string;             // Body text
  headingTextColor: string;      // Headings & titles
  tableHeaderTextColor: string;  // Table column headers
  accentTextColor: string;       // Accent labels & badges
  mutedTextColor: string;        // Captions & footnotes
}

export const TEXT_COLOR_THEMES: TextColorThemePreset[] = [
  {
    id: 'DEFAULT_SLATE',
    name: 'Executive Slate (Default)',
    description: 'Crisp, modern slate tones with high readability and balanced contrast.',
    textColor: '#0f172a',
    headingTextColor: '#0f172a',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#4f46e5',
    mutedTextColor: '#64748b',
  },
  {
    id: 'JET_BLACK',
    name: 'Ink-Saver Jet Black (100% Contrast)',
    description: 'Pure high-contrast black typography ideal for laser printing and xerox copies.',
    textColor: '#000000',
    headingTextColor: '#000000',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#000000',
    mutedTextColor: '#475569',
  },
  {
    id: 'MIDNIGHT_NAVY',
    name: 'Corporate Midnight Navy',
    description: 'Deep midnight blue tones for legal, enterprise B2B, and consulting invoices.',
    textColor: '#0f172a',
    headingTextColor: '#1e3a8a',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#2563eb',
    mutedTextColor: '#64748b',
  },
  {
    id: 'WARM_CHARCOAL',
    name: 'Warm Stone & Charcoal',
    description: 'Earthy warm charcoal tones giving a luxury, handcrafted, bespoke aesthetic.',
    textColor: '#292524',
    headingTextColor: '#1c1917',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#d97706',
    mutedTextColor: '#78716c',
  },
  {
    id: 'EMERALD_ACCENT',
    name: 'Botanical Forest & Emerald',
    description: 'Rich dark slate body paired with vibrant emerald headings for pharma & agro businesses.',
    textColor: '#064e3b',
    headingTextColor: '#065f46',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#059669',
    mutedTextColor: '#047857',
  },
  {
    id: 'ROYAL_PURPLE',
    name: 'Creative Luxe Amethyst',
    description: 'Deep violet headings and royal accents tailored for creative design and fashion studios.',
    textColor: '#1e1b4b',
    headingTextColor: '#4c1d95',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#7c3aed',
    mutedTextColor: '#6b21a8',
  },
  {
    id: 'CRIMSON_BOLD',
    name: 'Crimson Tech & Electronics',
    description: 'Sharp crimson headers and deep onyx body for electronics and appliance dealerships.',
    textColor: '#18181b',
    headingTextColor: '#991b1b',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#dc2626',
    mutedTextColor: '#71717a',
  }
];

export const POPULAR_TEXT_COLORS = [
  { name: 'Pure Black', hex: '#000000' },
  { name: 'Onyx Dark', hex: '#0f172a' },
  { name: 'Slate Gray', hex: '#334155' },
  { name: 'Midnight Navy', hex: '#1e3a8a' },
  { name: 'Royal Blue', hex: '#2563eb' },
  { name: 'Indigo Deep', hex: '#3730a3' },
  { name: 'Forest Emerald', hex: '#065f46' },
  { name: 'Ruby Dark', hex: '#991b1b' },
  { name: 'Amber Bronze', hex: '#92400e' },
  { name: 'Warm Charcoal', hex: '#292524' },
  { name: 'Amethyst Violet', hex: '#581c87' },
  { name: 'Teal Ocean', hex: '#115e59' },
  { name: 'Pure White', hex: '#ffffff' },
  { name: 'Muted Light Slate', hex: '#64748b' },
];

export function createDefaultCustomTemplate(customName = 'My Custom GST Template'): InvoiceTemplateConfig {
  return {
    id: `CUSTOM_${Date.now()}`,
    name: customName,
    category: 'CUSTOM',
    description: 'Customized invoice layout designed specifically according to your business branding and requirements.',
    badge: 'Custom',
    themeColor: '#4f46e5',
    headerColor: '#eef2ff',
    textColor: '#0f172a',
    headingTextColor: '#0f172a',
    tableHeaderTextColor: '#ffffff',
    accentTextColor: '#4f46e5',
    mutedTextColor: '#64748b',
    headerStyle: 'BANNER',
    fontFamily: 'sans',
    tableStyle: 'BORDERED',
    showLogo: true,
    showPaymentMode: true,
    showCashDetails: true,
    showUpiQr: true,
    showBankDetails: true,
    showSignature: true,
    showTerms: true,
    showNotes: true,
    showAmountInWords: true,
    showHsnSummaryTable: true,
    showCopyTypeBadge: true,
    showSerialNumber: true,
    showWarranty: true,
    showDescription: true,
    showBatchNumber: true,
    watermarkText: '',
    headerTagline: '',
    footerDeclaration: 'Certified that the particulars given above are true and correct.',
    createdAt: new Date().toISOString(),
  };
}

export function getAllTemplates(customTemplates?: InvoiceTemplateConfig[]): InvoiceTemplateConfig[] {
  const customs = customTemplates || [];
  return [...STANDARD_INVOICE_TEMPLATES, ...customs];
}

export function getTemplateById(templateId: string, customTemplates?: InvoiceTemplateConfig[]): InvoiceTemplateConfig {
  const all = getAllTemplates(customTemplates);
  return all.find(t => t.id === templateId) || STANDARD_INVOICE_TEMPLATES[0];
}
