import { Company, BusinessProfile, AppUser, Product, Party, Invoice, PurchaseBill, Expense, PaymentRecord } from '../types';
import { initialBusinessProfile, initialProducts, initialParties, initialInvoices, initialPurchaseBills, initialExpenses, initialAccountHeads, initialJournalEntries, initialPayments } from './mockData';
import { initialUsers, initialAuditLogs } from './rbacRules';

export interface CompanyStoreData {
  company: Company;
  business: BusinessProfile;
  users: AppUser[];
  products: Product[];
  parties: Party[];
  invoices: Invoice[];
  purchaseBills: PurchaseBill[];
  payments: PaymentRecord[];
  expenses: Expense[];
}

export const initialCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Bharat Tech & Solutions Pvt Ltd',
    tradeName: 'Bharat Electronics & Tech',
    gstin: '07AAAAA0000A1Z5',
    pan: 'AAAAA0000A',
    businessType: 'Private Limited • IT & Hardware',
    state: 'Delhi',
    stateCode: '07',
    city: 'New Delhi',
    address: 'Plot No. 42, Okhla Industrial Area Phase-III',
    pincode: '110020',
    phone: '+91 98765 43210',
    email: 'accounts@bharattech.in',
    financialYear: '2026-2027',
    currency: 'INR',
    currencySymbol: '₹',
    themeColor: 'indigo',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'comp-2',
    name: 'Royal Traders & Logistics LLP',
    tradeName: 'Royal FMCG Wholesale',
    gstin: '29ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    businessType: 'LLP • FMCG & Logistics',
    state: 'Karnataka',
    stateCode: '29',
    city: 'Bengaluru',
    address: 'No. 88, Yeshwanthpur APMC Yard, Outer Ring Road',
    pincode: '560022',
    phone: '+91 98450 11223',
    email: 'billing@royaltraders.in',
    financialYear: '2026-2027',
    currency: 'INR',
    currencySymbol: '₹',
    themeColor: 'emerald',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'comp-3',
    name: 'Kavya Electronics & Retail Hub',
    tradeName: 'Kavya Digital World',
    gstin: '27AABCK9988C1Z1',
    pan: 'AABCK9988C',
    businessType: 'Proprietorship • Retail POS',
    state: 'Maharashtra',
    stateCode: '27',
    city: 'Mumbai',
    address: 'Shop 14-16, Lamington Road, Grant Road East',
    pincode: '400007',
    phone: '+91 99201 88776',
    email: 'support@kavyaelectronics.com',
    financialYear: '2026-2027',
    currency: 'INR',
    currencySymbol: '₹',
    themeColor: 'amber',
    createdAt: '2026-02-01T00:00:00Z',
  }
];

// Company 2: Royal Traders initial profile & users
export const comp2BusinessProfile: BusinessProfile = {
  name: 'Royal Traders & Logistics LLP',
  tradeName: 'Royal FMCG Wholesale',
  gstin: '29ABCDE1234F1Z5',
  pan: 'ABCDE1234F',
  phone: '+91 98450 11223',
  email: 'billing@royaltraders.in',
  address: 'No. 88, Yeshwanthpur APMC Yard, Outer Ring Road',
  city: 'Bengaluru',
  state: 'Karnataka',
  stateCode: '29',
  pincode: '560022',
  website: 'https://royaltraders.in',
  currency: 'INR',
  currencySymbol: '₹',
  bankName: 'State Bank of India',
  accountNumber: '398822001144',
  ifscCode: 'SBIN0001811',
  branchName: 'Yeshwanthpur Branch, Bengaluru',
  upiId: 'royaltraders@sbi',
  invoicePrefix: 'RT/26-27/',
  nextInvoiceNumber: 201,
  defaultTerms: '1. Goods sold are as per APMC quality standards.\n2. Payment terms 15 days from delivery.\n3. Subject to Bengaluru jurisdiction.',
  defaultNotes: 'Thank you for choosing Royal Traders Wholesale!',
  enableEinvoice: true,
  enableEwayBill: true,
  einvoiceThresholdCr: 5,
  signatoryName: 'Rohan Hegde',
  signatoryDesignation: 'Managing Partner',
  showSignatureOnInvoice: true,
};

export const comp2Users: AppUser[] = [
  {
    id: 'usr-c2-1',
    name: 'Rohan Hegde',
    email: 'rohan@royaltraders.in',
    phone: '+91 98450 11223',
    role: 'ADMIN',
    roleTitle: 'Managing Partner / Admin',
    department: 'Executive Management',
    avatarBg: 'bg-emerald-600',
    avatarText: 'RH',
    isActive: true,
    password: 'admin',
    pin: '1111',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'usr-c2-2',
    name: 'Priya Nair',
    email: 'priya@royaltraders.in',
    phone: '+91 98450 44556',
    role: 'ACCOUNTANT',
    roleTitle: 'Senior GST Accountant',
    department: 'Accounts & Tax',
    avatarBg: 'bg-blue-600',
    avatarText: 'PN',
    isActive: true,
    password: 'acc',
    pin: '2222',
    createdAt: '2026-01-16T00:00:00Z',
  },
  {
    id: 'usr-c2-3',
    name: 'Karthik Rao',
    email: 'karthik@royaltraders.in',
    phone: '+91 98450 77889',
    role: 'SALESPERSON',
    roleTitle: 'B2B Sales Representative',
    department: 'Wholesale Sales',
    avatarBg: 'bg-amber-600',
    avatarText: 'KR',
    isActive: true,
    password: 'sales',
    pin: '3333',
    createdAt: '2026-01-17T00:00:00Z',
  }
];

export const comp2Products: Product[] = [
  {
    id: 'prod-c2-1',
    name: 'Fortune Sunlite Refined Sunflower Oil (15L Tin)',
    sku: 'FMCG-OIL-15L',
    barcode: '8901234990011',
    category: 'Edible Oils',
    hsnCode: '1512',
    unit: 'TIN',
    purchasePrice: 1650,
    sellingPrice: 1890,
    gstRate: 5,
    currentStock: 45,
    minStockAlert: 10,
    batches: [{ batchNumber: 'FS-2026-01', mfgDate: '2026-01-05', expiryDate: '2027-01-05', stock: 45, mrp: 2100 }],
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prod-c2-2',
    name: 'Daawat Rozana Super Basmati Rice (25kg Bag)',
    sku: 'FMCG-RICE-25KG',
    barcode: '8901234990022',
    category: 'Grains & Pulses',
    hsnCode: '1006',
    unit: 'BAG',
    purchasePrice: 1850,
    sellingPrice: 2150,
    gstRate: 5,
    currentStock: 60,
    minStockAlert: 15,
    batches: [{ batchNumber: 'DW-2026-R1', mfgDate: '2026-01-01', expiryDate: '2027-06-01', stock: 60, mrp: 2400 }],
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prod-c2-3',
    name: 'Aashirvaad Superior MP Sharbati Atta (10kg)',
    sku: 'FMCG-ATTA-10KG',
    barcode: '8901234990033',
    category: 'Grains & Pulses',
    hsnCode: '1101',
    unit: 'BAG',
    purchasePrice: 420,
    sellingPrice: 495,
    gstRate: 5,
    currentStock: 80,
    minStockAlert: 20,
    batches: [{ batchNumber: 'ASH-2026-A1', mfgDate: '2026-01-10', expiryDate: '2026-07-10', stock: 80, mrp: 550 }],
    createdAt: '2026-01-15T00:00:00Z',
  }
];

// Company 3: Kavya Electronics initial profile & users
export const comp3BusinessProfile: BusinessProfile = {
  name: 'Kavya Electronics & Retail Hub',
  tradeName: 'Kavya Digital World',
  gstin: '27AABCK9988C1Z1',
  pan: 'AABCK9988C',
  phone: '+91 99201 88776',
  email: 'support@kavyaelectronics.com',
  address: 'Shop 14-16, Lamington Road, Grant Road East',
  city: 'Mumbai',
  state: 'Maharashtra',
  stateCode: '27',
  pincode: '400007',
  website: 'https://kavyaelectronics.com',
  currency: 'INR',
  currencySymbol: '₹',
  bankName: 'ICICI Bank Ltd',
  accountNumber: '001105018992',
  ifscCode: 'ICIC0000011',
  branchName: 'Lamington Road Branch, Mumbai',
  upiId: 'kavyadigital@icici',
  invoicePrefix: 'KDW/26-27/',
  nextInvoiceNumber: 501,
  defaultTerms: '1. Manufacturer warranty applies to all electronic items.\n2. In case of manufacturing defect, return within 7 days with original bill.',
  defaultNotes: 'Thank you for shopping at Kavya Digital World!',
  enableEinvoice: false,
  enableEwayBill: true,
  einvoiceThresholdCr: 5,
  signatoryName: 'Kavya Deshmukh',
  signatoryDesignation: 'Proprietor',
  showSignatureOnInvoice: true,
};

export const comp3Users: AppUser[] = [
  {
    id: 'usr-c3-1',
    name: 'Kavya Deshmukh',
    email: 'kavya@kavyaelectronics.com',
    phone: '+91 99201 88776',
    role: 'ADMIN',
    roleTitle: 'Proprietor / Store Owner',
    department: 'Management',
    avatarBg: 'bg-amber-600',
    avatarText: 'KD',
    isActive: true,
    password: 'admin',
    pin: '1111',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'usr-c3-2',
    name: 'Sneha Patil',
    email: 'sneha@kavyaelectronics.com',
    phone: '+91 99201 33221',
    role: 'ACCOUNTANT',
    roleTitle: 'Billing & Accounts Executive',
    department: 'Accounts',
    avatarBg: 'bg-purple-600',
    avatarText: 'SP',
    isActive: true,
    password: 'acc',
    pin: '2222',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'usr-c3-3',
    name: 'Nilesh Sawant',
    email: 'nilesh@kavyaelectronics.com',
    phone: '+91 99201 55443',
    role: 'SALESPERSON',
    roleTitle: 'Retail Counter Salesman',
    department: 'POS Counter',
    avatarBg: 'bg-cyan-600',
    avatarText: 'NS',
    isActive: true,
    password: 'sales',
    pin: '3333',
    createdAt: '2026-02-01T00:00:00Z',
  }
];

export const comp3Products: Product[] = [
  {
    id: 'prod-c3-1',
    name: 'OnePlus Nord CE4 5G (8GB RAM, 128GB Storage)',
    sku: 'MOB-OP-CE4-128',
    barcode: '8901234771100',
    category: 'Smartphones & Tablets',
    hsnCode: '8517',
    unit: 'PCS',
    purchasePrice: 19500,
    sellingPrice: 22999,
    gstRate: 18,
    currentStock: 18,
    minStockAlert: 4,
    batches: [{ batchNumber: 'OP-2026-B1', mfgDate: '2026-01-20', expiryDate: '2029-01-20', stock: 18, mrp: 24999 }],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'prod-c3-2',
    name: 'boAt Airdopes 141 Bluetooth TWS Earbuds',
    sku: 'AUD-BOAT-141',
    barcode: '8901234771111',
    category: 'Audio & Wearables',
    hsnCode: '8518',
    unit: 'PCS',
    purchasePrice: 850,
    sellingPrice: 1299,
    gstRate: 18,
    currentStock: 35,
    minStockAlert: 8,
    batches: [{ batchNumber: 'BT-2026-E1', mfgDate: '2026-01-15', expiryDate: '2028-01-15', stock: 35, mrp: 2990 }],
    createdAt: '2026-02-01T00:00:00Z',
  }
];
